name: Build and publish Docker image
on:
  push:
    branches: [main, beta]
  release:
    types:
      - published

jobs:
  yarn_build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: '18'
      - name: Cache node modules
        uses: actions/cache@v2
        id: cache
        env:
          cache-name: cache-node-modules-v2
        with:
          path: node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('yarn.lock') }}
      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: yarn install --frozen-lockfile
      - name: Build
        run: yarn build
      - name: Lint
        run: yarn lint

  semantic-release:
    if: ${{ github.ref == 'refs/heads/main' || github.ref == 'refs/heads/beta' }}
    name: Create a semantic release
    runs-on: ubuntu-latest
    needs:
      - yarn_build
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_TOKEN }}
      - uses: actions/setup-node@v2
        with:
          node-version: '18'
      - name: Cache node modules
        uses: actions/cache@v2
        id: cache
        env:
          cache-name: cache-node-modules-v2
        with:
          path: node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('yarn.lock') }}
      - name: Install semantic-release globally
        run: sudo npm install --prefer-offline --no-audit --global semantic-release@^17.4.4 @semantic-release/exec@^5.0.0 @semantic-release/git@^9.0.0 conventional-changelog-conventionalcommits@^4.6.3
      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: yarn install --frozen-lockfile
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.BOT_TOKEN }}
          GIT_AUTHOR_NAME: ${{ secrets.BUMP_GIT_NAME }}
          GIT_AUTHOR_EMAIL: ${{ secrets.BUMP_GIT_EMAIL }}
          GIT_COMMITTER_NAME: ${{ secrets.BUMP_GIT_NAME }}
          GIT_COMMITTER_EMAIL: ${{ secrets.BUMP_GIT_EMAIL }}
        run: yarn semantic-release
  sync_main_to_beta:
    if: ${{ github.ref == 'refs/heads/main' }}
    name: Sync branch `main` to `beta` (fast-forward enabled)
    runs-on: ubuntu-latest
    needs:
      - semantic-release
    steps:
      - name: Keep `beta` up to date with `main` (fast-forward enabled)
        uses: jojomatik/sync-branch@v1
        with:
          git_committer_name: ${{ secrets.BUMP_GIT_NAME }}
          git_committer_email: ${{ secrets.BUMP_GIT_EMAIL }}
          github_token: ${{ secrets.GH_TOKEN }}
  sync_beta_to_updates:
    if: ${{ github.ref == 'refs/heads/beta' }}
    name: Sync branch `beta` to `updates` (fast-forward enabled)
    runs-on: ubuntu-latest
    needs:
      - semantic-release
    steps:
      - name: Keep `updates` up to date with `beta` (fast-forward enabled)
        uses: jojomatik/sync-branch@v1
        with:
          target: "updates"
          git_committer_name: ${{ secrets.BUMP_GIT_NAME }}
          git_committer_email: ${{ secrets.BUMP_GIT_EMAIL }}
          github_token: ${{ secrets.GH_TOKEN }}
